# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: _canvas.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    '_canvas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\r_canvas.proto\"Q\n\rCanvasRequest\x12$\n\x06tracks\x18\x01 \x03(\x0b\x32\x14.CanvasRequest.Track\x1a\x1a\n\x05Track\x12\x11\n\ttrack_uri\x18\x01 \x01(\t\"\x98\x02\n\x0e\x43\x61nvasResponse\x12(\n\x08\x63\x61nvases\x18\x01 \x03(\x0b\x32\x16.CanvasResponse.Canvas\x1a\xdb\x01\n\x06\x43\x61nvas\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\ncanvas_url\x18\x02 \x01(\t\x12\x11\n\ttrack_uri\x18\x05 \x01(\t\x12-\n\x06\x61rtist\x18\x06 \x01(\x0b\x32\x1d.CanvasResponse.Canvas.Artist\x12\x10\n\x08other_id\x18\t \x01(\t\x12\x12\n\ncanvas_uri\x18\x0b \x01(\t\x1aI\n\x06\x41rtist\x12\x12\n\nartist_uri\x18\x01 \x01(\t\x12\x13\n\x0b\x61rtist_name\x18\x02 \x01(\t\x12\x16\n\x0e\x61rtist_img_url\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, '_canvas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CANVASREQUEST']._serialized_start=17
  _globals['_CANVASREQUEST']._serialized_end=98
  _globals['_CANVASREQUEST_TRACK']._serialized_start=72
  _globals['_CANVASREQUEST_TRACK']._serialized_end=98
  _globals['_CANVASRESPONSE']._serialized_start=101
  _globals['_CANVASRESPONSE']._serialized_end=381
  _globals['_CANVASRESPONSE_CANVAS']._serialized_start=162
  _globals['_CANVASRESPONSE_CANVAS']._serialized_end=381
  _globals['_CANVASRESPONSE_CANVAS_ARTIST']._serialized_start=308
  _globals['_CANVASRESPONSE_CANVAS_ARTIST']._serialized_end=381
# @@protoc_insertion_point(module_scope)
